name: SweetTimer
version: '${version}'
main: top.mrxiaom.sweet.timer.SweetTimer
api-version: 1.13
depend: []
softdepend: 
  - PlaceholderAPI
authors: [ MrXiaoM ]
folia-supported: true
# PluginBase Libraries ${libraries_config}
commands:
  sweettimer:
    description: 'The main command of SweetTimer'
    aliases: [ stimer, timer ]
